apiVersion: v1
kind: Pod
metadata:
  name: ng
  namespace: polyaxon
spec:
  containers:
    - name: ng
      image: nginx:1.14.2
      securityContext:
        capabilities:
          add: ["SYS_RAWIO"]
#      resources:
#        limits:
#          hostdev.k8s.io/dev_mem: 1
