apiVersion: v1
kind: Pod
metadata:
  name: ng-nohostdev
  namespace: polyaxon
spec:
  containers:
    - name: ng
      image: nginx:1.14.2
      securityContext:
        capabilities:
          add: ["SYS_RAWIO"]
